include /etc/nginx/conf.d/config/maps/loggable.conf;
include /etc/nginx/conf.d/config/maps/loglevels.conf;
include /etc/nginx/conf.d/config/maps/blacklist.conf;

include /etc/nginx/conf.d/config/log_formats/json.conf;
include /etc/nginx/conf.d/config/log_formats/simple.conf;

server {
    listen [::]:80 default_server ipv6only=on;
    listen 0.0.0.0:80 default_server;

    index index.php;
    server_name _;
    root /var/www/app/public;

    charset utf-8;

    # redefine access/error logs
    access_log /var/log/nginx/server.access.log simple if=$loggable;
    error_log  /var/log/nginx/server.error.log  warn;

    ## Disable ETag Header
    # etag off;

    ### requires blacklist.conf
    if ($bad_referer) {
      return 444;
    }

    include /etc/nginx/conf.d/config/paths/forbidden.conf;

    location / {
      try_files $uri $uri/ /index.php$is_args$args;
    }

    # optionally disable falling back to PHP script for the asset directories;
    # nginx will return a 404 error when files are not found instead of passing the
    # request to Symfony (improves performance but Symfony's 404 page is not displayed)
    # location /bundles {
    #   try_files $uri =404;
    # }

    location ~ ^/index\.php(/|$) {
      fastcgi_pass nginx:9000;
      fastcgi_index index.php;

      # regex to split $uri to $fastcgi_script_name and $fastcgi_path_info
      fastcgi_split_path_info ^(.+\.php)(/.*)$;
      # default fastcgi_params
      include fastcgi_params;

      # fastcgi params settings (used by supervisor)
      fastcgi_buffer_size 128k;
      fastcgi_buffers 4 256k;
      fastcgi_busy_buffers_size 256k;

      fastcgi_connect_timeout 60;
      fastcgi_read_timeout 300;

      # fastcgi params
      fastcgi_param PATH_INFO $fastcgi_path_info;
      fastcgi_param DOCUMENT_ROOT $realpath_root;
      # for symlink cache issue (If you update your symlink for the current to a new release, your application will still be point to the older release.)
      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;


      # Prevents URIs that include the front controller. This will 404:
      # http://domain.tld/index.php/some-path
      # Remove the internal directive to allow URIs like this
      internal;
    }

    # return 404 for all other php files not matching the front controller
    # this prevents access to other php files you don't want to be accessible.
    location ~ \.php$ {
      return 404;
    }
}
