volumes:
  dbdata:
    name: ${PROJECT_NAME}_dbdata
  node_modules:
    name: ${PROJECT_NAME}_node_modules

networks:
  default:
    name: ${PROJECT_NAME}_backend
    driver: bridge

services:
  ########################
  # Development
  ########################
  php:
    container_name: ${PROJECT_NAME}-php
    image: ${PROJECT_NAME}-php:0.0.1
    build:
      context: ./.docker/service/php
      args:
        - PHP_VER=${PHP_VER:-8.4-fpm-trixie}
        - UID=${UID}
        - GID=${GID}
        - UNAME=${UNAME}
        - GNAME=${GNAME}
        - PASS=${PASS}
      target: develop
    init: true
    working_dir: ${WORKDIR:-/var/www/app}
    user: ${UID:-1000}
    network_mode: service:nginx
    volumes:
      - ./app:${WORKDIR:-/var/www/app}
      # read git commit version for version manager
      - ./.git:${WORKDIR:-/var/www/app}/.git
    depends_on:
      db:
        condition: service_healthy
      nginx:
        condition: service_started


  ########################
  # Webserver
  ########################
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:${NGINX_VER:-latest}
    restart: unless-stopped
    ports:
      - "${NGINX_PORT_HOST:-80}:80"
      - "${PHP_PORT_HOST:-9000}:${PHP_PORT_CONTAINER:-9000}"
    volumes:
      - ./app:${WORKDIR:-/var/www/app}
      - ./.docker/data/logs/nginx:/var/log/nginx
      - ./.docker/service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ########################
  # Database
  ########################
  db:
    container_name: ${PROJECT_NAME}-db
    image: ${DB_IMAGE:-mariadb}:${DB_IMAGE_VER:-12.2}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${DB_NAME:-timebot}
      - MARIADB_USER=${DB_USER:-admin}
      - MARIADB_PASSWORD=${DB_PW:-admin}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    expose:
      - ${DB_PORT_CONTAINER:-3306}
    volumes:
      - dbdata:${DB_VOLUME_PATH:-/var/lib/mysql}
      - ./.docker/service/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  ########################
  # Database UI
  ########################
  adminer:
    container_name:  ${PROJECT_NAME}-adminer
    image: adminer:latest
    environment:
      # https://github.com/vrana/adminer/tree/master/plugins
      ADMINER_PLUGINS: "tables-filter edit-calendar edit-textarea"
      # https://github.com/vrana/adminer/tree/master/designs
      # ADMINER_DESIGN: "nicu"
      # default server entry in the login form
      ADMINER_SERVERS_JSON: '[{"server":"db:3306","username":"${DB_USER}","password":"${DB_PW}","db":"${DB_NAME}","label":"Local Dev (ENV)"}]'
    restart: unless-stopped
    user: adminer
    ports:
      - "${ADMINER_PORT_HOST:-8080}:8080" # web ui
    volumes:
      - ./.docker/service/adminer/plugins/autologin.php:/var/www/html/plugins/autologin.php
      - ./.docker/service/adminer/plugins-enabled/autologin.php:/var/www/html/plugins-enabled/autologin.php


  ########################
  # Mail Receiver
  ########################
  mailpit:
    container_name: ${PROJECT_NAME}-mailpit
    image: axllent/mailpit:latest
    restart: unless-stopped
    logging:
      driver: 'none' # disable saving logs
    expose:
      - 1025 # smtp server
    ports:
      - "8025:8025" # web ui
    environment:
      TZ: Europe/Berlin

  ########################
  # Node
  ########################
  node:
    container_name: ${PROJECT_NAME}-node
    image: ${PROJECT_NAME}-node:0.0.1
    build:
      context: .
      dockerfile: .docker/service/node/Dockerfile
      args:
        - PROJECT_NAME=${PROJECT_NAME}
        - NODE_VER=${NODE_VER}
        - UID=${UID}
        - GID=${GID}
        - UNAME=${UNAME}
        - GNAME=${GNAME}
        - PASS=${PASS}
      target: develop
    init: true
    user: ${UID:-1000}
    entrypoint: /bin/bash
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app

