services:
  devcontainer:
    container_name: ${PROJECT_NAME}-devcontainer
    build:
      # context is the first included compose.yaml in devcontainer.json
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - BASE_IMAGE=${PROJECT_NAME}-php:0.0.1
        - UNAME=${UNAME}
        - NODE_VERSION=${NODE_VERSION}
    init: true
    working_dir: /workspace
    # share the same networking space with the php container so both can use 'localhost' on curl (no custom hostname)
    network_mode: "service:php"
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
      # dont use host symlinks here, they cause issues with file watching since the symlink path may not exist inside the devcontainer
      # - ~/.gitconfig:/home/${UNAME}/.gitconfig:ro
      # dont mount .ssh dir here, the ssh-agent has everything we need
      # - ~/.ssh/known_hosts:/home/${UNAME}/.ssh/known_hosts
