admin_api_v1_controllers:
  resource: ../../src/Controller/AdminApi
  type: attribute

admin_internal_controllers:
  resource: ../../src/Controller/Admin/Internal
  type: attribute

admin_view_controllers:
  resource: ../../src/Controller/Admin/View
  type: attribute
  prefix:
    'en': '' # don't prefix URLs for English, the default locale
    'de' : '/de'
  # defaults:
  #   _locale: '%app.default_locale%' # already set via default_locale
  # requirements:
  #   _locale: '%app.supported_locales%' # already set via enabled_locales

controllers:
  resource:
    path: ../../src/Controller/Frontend
    namespace: App\Controller\Frontend
  type: attribute
  prefix:
    'en': '' # don't prefix URLs for English, the default locale
    'de' : '/de'
  # defaults:
  #   _locale: '%app.default_locale%' # already set via default_locale
  # requirements:
  #   _locale: '%app.supported_locales%' # already set via enabled_locales

kernel:
  resource: App\Kernel
  type: attribute
