/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLucideChevronFirst: typeof import('~icons/lucide/chevron-first')['default']
    IconLucideChevronLast: typeof import('~icons/lucide/chevron-last')['default']
  }
}
