security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      # Ensure dev tools and static assets are always allowed
      pattern: ^/(_profiler|_wdt|assets|build)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      remember_me:
        name: REMEMBERME # cookie name
        secret: "%kernel.secret%" # required
        lifetime: 604800 # 1 week in seconds
        signature_properties: ["password", "updatedAt"] # cookie no longer valid if these properties are changing
        # by default, the feature is enabled by checking a
        # checkbox in the login form (see below), uncomment the
        # following line to always enable it.
        #always_remember_me: true
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        # change the page where the user is redirected to if no previous page was stored in the session
        default_target_path: admin_dashboard
        always_use_default_target_path: true
      logout:
        path: app_logout
        enable_csrf: true
        # where to redirect after logout
        target: app_login

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall

      # https://symfony.com/doc/current/security/impersonating_user.html
      switch_user:
        role: ROLE_ALLOWED_TO_SWITCH
        parameter: '%app.switch_user.parameter%'
    api:
      stateless: true

  # Users with the ROLE_ADMIN role will also have the ROLE_USER role.
  # Users with ROLE_SUPER_ADMIN, will automatically have ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH and ROLE_USER (inherited from ROLE_ADMIN).
  role_hierarchy:
    # can see the status of the importer/exporter
    ROLE_MEMBER: ROLE_USER
    # can see the logs of the importer/exporter and restart them
    ROLE_ADMIN: ROLE_MEMBER
    # can see tokens and hidden menus
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: '^/admin', roles: ROLE_MEMBER }
    - { path: ^/api/auth, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY] }

when@test:
  security:
    password_hashers:
      # Password hashers are resource-intensive by design to ensure security.
      # In tests, it's safe to reduce their cost to improve performance.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
